In [6]:
import torch

#Create a Tensor
torch.tensor([[1,2],[2,1]])

tensor([[1, 2],
        [2, 1]])

In [2]:
#Create a Tensor from FLoats
torch.FloatTensor([[1,2],[2,1]])

tensor([[1., 2.],
        [2., 1.]])

In [5]:
#Define Tensor Data Type
torch.tensor([[1,2],[2,1]], dtype=torch.bool)

tensor([[True, True],
        [True, True]])

In [8]:
#Auto create tensors with random numbers
#(row, col)
torch.rand(3,2)

tensor([[0.5993, 0.1287],
        [0.8306, 0.0817],
        [0.7487, 0.3669]])

In [10]:
#Auto create full of ones
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
#Some Useful Tensor operations

In [12]:
#Addition
x = torch.tensor([[2,3], [1,2]])
print(x)
print(f'sum: {x.sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 8


In [13]:
#Transpose of a Tensor
x.t()

tensor([[2, 1],
        [3, 2]])

In [14]:
#Shape of each dimension
x.size()

torch.Size([2, 2])

In [16]:
#Adding tensors
y = torch.tensor([[2,2],[5,1]])
z = x.add(y)
z

tensor([[4, 5],
        [6, 3]])

In [18]:
#Adding tensors in Place
#Less code
x.add_(y)

tensor([[4, 5],
        [6, 3]])

 PyTorch has 3 major powers
1. Running operations on GPU
2. AutoGrad : Automatic differentiation
3. A set of tools to build Neural Networks

In [20]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device\
("cpu")
device

device(type='cpu')

Common Issues
1. Doing operations between GPU and CPU Tensors is not allowed
2. Size mismatch between Tensors occurs often and is (almost everytime) easy to fix
3. Running out of GPU memory